### ISSUE TITLE
Cant save more than 17 packages

### ISSUE THREAD

**Issue by kafle1** [tulu/chrome-extension-npm-faves#43]
I am unable to save more than 17 packages in this extension. After the 17th package whenever i try to save new package it says saved but actually its is not saved in the extension

**Comment by tulu** [comment]
Hi @kafle1, so sorry for the late response. I can see that the quota limit fix was merged to the main branch a while ago but I never published a new version... my bad. In the next few days I'll test it just in case and publish it.
